// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // 🔥 Version 8.6.1 is better for your latest Android Studio
    id 'com.android.application' version '8.6.1' apply false
    id 'com.android.library' version '8.6.1' apply false

    // ✅ Yahan Kotlin plugin add karein (Version 2.2.0 ya higher)
    // Ye aapke metadata binary version error ko fix karega
    id 'org.jetbrains.kotlin.android' version '2.2.0' apply false

    // 🔥 Use the latest stable Google Services
    id 'com.google.gms.google-services' version '4.4.2' apply false

    // 🔥 Firebase Crashlytics plugin
    id 'com.google.firebase.crashlytics' version '3.0.2' apply false
}

// You can also add global repositories or configuration if needed
task clean(type: Delete) {
    delete rootProject.buildDir
}