# Memory Settings
org.gradle.jvmargs=-Xmx4g -Xms1g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC

# Build speed aur reliability
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=true

# R8/Minify stability
android.enableR8.fullMode=true
org.gradle.workers.max=2

# ? ADD THESE 2 LINES FOR BETTER PERFORMANCE & STABILITY
# 1. Configuration cache enable karein (Build time drastically kam hoga)
org.gradle.configuration-cache=true
# 2. Build ka timeout bada dein (Agar network ya complex build hai)
org.gradle.internal.http.socketTimeout=120000

# Aapki API Key
API_KEY=XBwe0uVt6gSChcA14IxZyGGkT3wiQCY79vYW3QbSVJOZbg0aLajuaDBK