name: Status Expiry Monitor

on:
  schedule:
    - cron: '*/30 * * * *' # Har 30 minute baad script automatically chalegi
  workflow_dispatch: # Taake aap Actions tab se manually bhi run kar sakain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        # Ab humein Firebase Admin SDK chahiye jo notify.py mein use ho rahi hai
        run: pip install firebase-admin

      - name: Run Script
        env:
          # GitHub Secrets se Service Account JSON utha kar script ko dena
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python notify.py
